Repository Ideas-Digitales/socomarca-backend, pull requests merged in 2025-06, with the labels that each got.

#81 endpoint products, json result
  app/Http/Controllers/Api/ProductController.php
  app/Http/Resources/Products/ProductCollection.php
  app/Http/Resources/Products/ProductResource.php
  database/factories/PriceFactory.php
  database/factories/ProductFactory.php
  database/migrations/2025_06_04_183743_add_stock_to_prices_table.php
  database/migrations/2025_06_04_183758_add_image_to_products_table.php
  database/seeders/DatabaseSeeder.php
Labels: enhancement

#77 feat: Agrega configuración de Webpay y actualiza rutas
  .env.example
  app/Http/Controllers/Api/OrderController.php
  app/Http/Controllers/Api/WebpayController.php
  app/Services/WebpayService.php
  routes/api.php
  routes/web.php
Labels: bug

#84 refactor: reubica la ruta catch-all al final del archivo de rutas y elimina la versión anterior
  routes/api.php
Labels: bug

#86 fix: rango precios se envia request al collection
  app/Http/Resources/Products/ProductCollection.php
Labels: bug

#83 feat: agregar permisos y role
  app/Http/Controllers/AuthController.php
  app/Models/User.php
  database/seeders/RolesAndPermissionsSeeder.php
Labels: enhancement

#96 Fix cart
  app/Http/Controllers/Api/CartItemController.php
  app/Http/Resources/CartItems/CartItemResource.php
Labels: bug

#95 feat: agregar seeder roles permisos y regiones y comunas
  database/factories/MunicipalityFactory.php
  database/factories/RegionFactory.php
  database/seeders/DatabaseSeeder.php
  database/seeders/RegionSeeder.php
  storage/app/private/fake_seed_data/municipalities.json
  storage/app/private/fake_seed_data/regions.json
Labels: enhancement

#104 modificar seed de roles y permisos, asignar a usuarios
  database/seeders/RolesAndPermissionsSeeder.php
Labels: enhancement

#101 test: #98 - agrega pruebas para la creación de usuario
  tests/Feature/PersonalInformationTest.php
Labels: enhancement

#116 fix: #114 - Error al agregar producto al carrito y pruebas
  README.md
  app/Http/Controllers/Api/CartItemController.php
  app/Http/Requests/CartItems/DestroyRequest.php
  app/Models/CartItem.php
  tests/Feature/CartItemTest.php
Labels: bug

#115 agregar test para productos
  app/Models/Product.php
  database/factories/MunicipalityFactory.php
  database/seeders/DatabaseSeeder.php
  database/seeders/RolesAndPermissionsSeeder.php
  tests/Feature/ProductTest.php
Labels: bug, enhancement

#125 refactor: #122 - Unificar endpoints de pago de la orden
  app/Http/Controllers/Api/OrderController.php
  app/Http/Requests/Orders/PayOrderRequest.php
  routes/api.php
Labels: enhancement

#128 refactor: #171 - Mejora en la gestión de direcciones y validaciones d…
  app/Http/Controllers/Api/AddressController.php
  app/Http/Controllers/Api/OrderController.php
  app/Http/Controllers/Api/UserController.php
  app/Http/Requests/Addresses/IndexRequest.php
  app/Http/Requests/Orders/PayOrderRequest.php
  app/Http/Resources/Addresses/AddressResource.php
  app/Http/Resources/Users/UserResource.php
  database/seeders/AddressSeeder.php
Labels: enhancement

#130 fix: corregir test user addresslist , y permisos
  database/seeders/RolesAndPermissionsSeeder.php
  tests/Feature/AddressTest.php
Labels: bug

#135 vaciar carrito
  app/Http/Controllers/Api/CartController.php
  app/Http/Controllers/Api/CartItemController.php
  app/Models/User.php
  routes/api.php
  tests/Feature/CartItemTest.php
Labels: enhancement

#137 test: Mejora las pruebas de pago de órdenes al incluir la dirección y el método de pago
  app/Http/Controllers/Api/OrderController.php
  app/Http/Requests/Orders/IndexRequest.php
  database/factories/OrderFactory.php
  tests/Feature/OrderTest.php
Labels: enhancement

#142 agregar alias a direcciones, modificar resultado json
  app/Http/Controllers/Api/AddressController.php
  app/Http/Requests/Addresses/StoreRequest.php
  app/Http/Requests/Addresses/UpdateRequest.php
  app/Http/Resources/Addresses/AddressResource.php
  app/Models/Address.php
  database/migrations/2025_06_16_201824_add_alias_to_addresses_table.php
  tests/Feature/AddressTest.php
Labels: enhancement

#161 feat: #149 - Agrega funcionalidad de búsqueda y filtrado de usuarios
  app/Http/Controllers/Api/UserController.php
  app/Http/Resources/Users/UserCollection.php
  app/Models/User.php
  routes/api.php
  tests/Feature/UserTest.php
Labels: enhancement

#159 fix: favoritos json actualizado
  app/Http/Controllers/Api/FavoriteController.php
  app/Http/Requests/Favorites/StoreRequest.php
  app/Http/Resources/Favorites/FavoriteResource.php
  app/Http/Resources/FavoritesList/FavoriteListResource.php
  app/Models/Favorite.php
  app/Rules/ProductHasUnit.php
  database/factories/FavoriteFactory.php
  database/migrations/2025_06_18_120842_add_unit_to_favorites.php
  tests/Feature/FavoriteTest.php
Labels: bug

#169 Feat: CRUD para la gestión de FAQs
  app/Http/Controllers/Api/FaqController.php
  app/Http/Requests/Faq/DestroyRequest.php
  app/Http/Requests/Faq/SearchRequest.php
  app/Http/Requests/Faq/StoreRequest.php
  app/Http/Requests/Faq/UpdateRequest.php
  app/Http/Resources/Faq/FaqCollection.php
  app/Http/Resources/Faq/FaqResource.php
  app/Models/Faq.php
  database/factories/FaqFactory.php
  database/migrations/2025_06_20_132726_create_faqs_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/FaqSeeder.php
  database/seeders/RolesAndPermissionsSeeder.php
  routes/api.php
  tests/Feature/FaqTest.php
Labels: enhancement

#168 CRUD para el administrador de usuarios
  README.md
  app/Http/Controllers/Api/UserController.php
  app/Http/Requests/AuthRequest.php
  app/Http/Requests/Users/DestroyRequest.php
  app/Http/Requests/Users/StoreRequest.php
  app/Http/Requests/Users/UpdateRequest.php
  app/Http/Resources/Users/UserResource.php
  app/Mail/UserNotificationMail.php
  app/Models/User.php
  app/Rules/ValidateRut.php
  resources/views/emails/user-notification.blade.php
  tests/Feature/AdminUserTest.php
Labels: enhancement

#181 Refactoriza la obtención de datos de precios en FavoriteResource para mejorar la legibilidad y eficiencia del código.
  app/Http/Resources/Favorites/FavoriteResource.php
Labels: enhancement

#190 feat: agregar funcionalidad para añadir productos de una orden al carrito
  app/Http/Controllers/Api/CartController.php
  app/Http/Requests/CartItems/AddOrderToCartRequest.php
  database/factories/OrderItemFactory.php
  routes/api.php
  tests/Feature/CartItemTest.php
Labels: enhancement

#189 refactor busqueda por producto filtros, test
  app/Http/Controllers/Api/ProductController.php
  app/Http/Resources/Products/ProductCollection.php
  app/Models/Product.php
  routes/api.php
  tests/Feature/ProductTest.php
Labels: bug

#188 modifacion parcial direccion, seeder modificados, regiones, comunas
  app/Http/Controllers/Api/AddressController.php
  app/Http/Requests/Addresses/PatchRequest.php
  database/migrations/2025_06_25_174900_add_status_to_municioalities_table.php
  database/seeders/RegionSeeder.php
  routes/api.php
Labels: enhancement

#192 Adds ChileanBundle and improves user creation tests
  composer.json
  composer.lock
  tests/Feature/AdminUserTest.php
  tests/Feature/PersonalInformationTest.php
  tests/TestCase.php
Labels: bug
